export const ICON_PATH = '/imgs/markers/'

export const DEFAULTS = { icon: 'marker-default.png', color: '#5cba9d' }

export const SPECIES_COLORS: [string, string][] = [
  ['no-determinable', '#a0a0a0'],
  ['no-determinado', '#a0a0a0'],
  ['jacaranda-mimosifolia', '#9798fb'],
  ['persea-americana', '#f8ff92'],
  ['liquidambar- styraciflua', '#f83a3a'],
  ['ceiba-speciosa', '#fb7a9b'],
  ['syagrus-romanzoffiana', '#788059'],
  ['erythrina-cristagalli', '#e6262b'],
  ['morus-alba', '#28316f'],
  ['handroanthus-impetiginosa', '#fb7a9b'],
  ['tabebuia-chrysotricha', '#ffd500'],
  ['ginkgo-biloba', '#f9d11f'],
  ['bauhinia-forficata', '#538036'],
  ['bauhinia-variegata', '#538036'],
  ['peltophorum-dubium', '#ffd500'],
  ['celtis-ehrembergiana', '#e79737'],
  ['acer-palmatum', '#f83a3a'],
  ['acacia-caven', '#ffd500'],
  ['citrus-aurantifolia', '#89b833'],
  ['citrus-aurantium', '#ffaf1f'],
  ['citrus-limon', '#f7d020'],
  ['citrus-paradisi', '#ffdb15'],
  ['citrus-reticulata', '#ffaf1f'],
  ['citrus-sinensis', '#ffaf1f'],
  ['erythrina-falcata', '#e6262b'],
  ['morus-alba-var-pendula', '#28316f'],
  ['morus-nigra', '#28316f'],
  ['tecoma-stans', '#ffd500'],
  ['morus-sp', '#28316f'],
  ['citrus sp', '#ffaf1f'],
  ['mangifera-sp', '#f76619'],
  ['mangifera-indica', '#f76619'],
  ['citrus-tangerina', '#ffaf1f'],
  ['plantera-vacia', '#d6d6d7'],
  ['handroanthus-ochraceus', '#ffd500'],
  ['tabebuia-rosea', '#fb7a9b'],
  ['erythrina-variegata', '#e6262b'],
]

export const SPECIES_ICONS: [string, string][] = [
  ['no-determinable', 'marker-sin-especie.png'],
  ['no-determinado', 'marker-sin-especie.png'],
  ['jacaranda-mimosifolia', 'marker-violeta.png'],
  ['persea-americana', 'marker-palta.png'],
  ['liquidambar- styraciflua', 'marker-rojo.png'],
  ['ceiba-speciosa', 'marker-rosa.png'],
  ['syagrus-romanzoffiana', 'marker-syagrus.png'],
  ['erythrina-cristagalli', 'marker-ceibo.png'],
  ['morus-alba', 'marker-morus.png'],
  ['handroanthus-impetiginosa', 'marker-rosa.png'],
  ['tabebuia-chrysotricha', 'marker-amarillo.png'],
  ['ginkgo-biloba', 'marker-ginkgo.png'],
  ['bauhinia-forficata', 'marker-bauhinia.png'],
  ['bauhinia-variegata', 'marker-bauhinia.png'],
  ['peltophorum-dubium', 'marker-amarillo.png'],
  ['celtis-ehrembergiana', 'marker-tala.png'],
  ['acer-palmatum', 'marker-rojo.png'],
  ['acacia-caven', 'marker-amarillo.png'],
  ['citrus-aurantifolia', 'marker-lima.png'],
  ['citrus-aurantium', 'marker-naranjo-amargo.png'],
  ['citrus-limon', 'marker-limon.png'],
  ['citrus-paradisi', 'marker-pomelo.png'],
  ['citrus-reticulata', 'marker-citrus.png'],
  ['citrus-sinensis', 'marker-naranjo-dulce.png'],
  ['erythrina-falcata', 'marker-ceibo.png'],
  ['morus-alba-var-pendula', 'marker-morus.png'],
  ['morus-nigra', 'marker-morus.png'],
  ['tecoma-stans', 'marker-amarillo.png'],
  ['morus-sp', 'marker-morus.png'],
  ['citrus sp', 'marker-citrus.png'],
  ['mangifera-sp', 'marker-naranja.png'],
  ['mangifera-indica', 'marker-naranja.png'],
  ['citrus-tangerina', 'marker-citrus.png'],
  ['plantera-vacia', 'marker-vacia.png'],
  ['handroanthus-ochraceus', 'marker-amarillo.png'],
  ['tabebuia-rosea', 'marker-rosa.png'],
  ['erythrina-variegata', 'marker-ceibo.png'],
]