export const ICON_PATH = '/imgs/markers/'

type SpeciesStyle = { icon: string, color: string }

const speciesStyles: Record<string, SpeciesStyle> = {
  'no-determinable': { icon: 'marker-sin-especie.png', color: '#a0a0a0' },
  'no-determinado': { icon: 'marker-sin-especie.png', color: '#a0a0a0' },
  'jacaranda-mimosifolia': { icon: 'marker-violeta.png', color: '#9798fb' },
  'persea-americana': { icon: 'marker-palta.png', color: '#f8ff92' },
  'liquidambar- styraciflua': { icon: 'marker-rojo.png', color: '#f83a3a' },
  'ceiba-speciosa': { icon: 'marker-rosa.png', color: '#fb7a9b' },
  'syagrus-romanzoffiana': { icon: 'marker-syagrus.png', color: '#788059' },
  'erythrina-cristagalli': { icon: 'marker-ceibo.png', color: '#e6262b' },
  'morus-alba': { icon: 'marker-morus.png', color: '#28316f' },
  'handroanthus-impetiginosa': { icon: 'marker-rosa.png', color: '#fb7a9b' },
  'tabebuia-chrysotricha': { icon: 'marker-amarillo.png', color: '#ffd500' },
  'ginkgo-biloba': { icon: 'marker-ginkgo.png', color: '#f9d11f' },
  'bauhinia-forficata': { icon: 'marker-bauhinia.png', color: '#538036' },
  'bauhinia-variegata': { icon: 'marker-bauhinia.png', color: '#538036' },
  'peltophorum-dubium': { icon: 'marker-amarillo.png', color: '#ffd500' },
  'celtis-ehrembergiana': { icon: 'marker-tala.png', color: '#e79737' },
  'acer-palmatum': { icon: 'marker-rojo.png', color: '#f83a3a' },
  'acacia-caven': { icon: 'marker-amarillo.png', color: '#ffd500' },
  'citrus-aurantifolia': { icon: 'marker-lima.png', color: '#89b833' },
  'citrus-aurantium': { icon: 'marker-naranjo-amargo.png', color: '#ffaf1f' },
  'citrus-limon': { icon: 'marker-limon.png', color: '#f7d020' },
  'citrus-paradisi': { icon: 'marker-pomelo.png', color: '#ffdb15' },
  'citrus-reticulata': { icon: 'marker-citrus.png', color: '#ffaf1f' },
  'citrus-sinensis': { icon: 'marker-naranjo-dulce.png', color: '#ffaf1f' },
  'erythrina-falcata': { icon: 'marker-ceibo.png', color: '#e6262b' },
  'morus-alba-var-pendula': { icon: 'marker-morus.png', color: '#28316f' },
  'morus-nigra': { icon: 'marker-morus.png', color: '#28316f' },
  'tecoma-stans': { icon: 'marker-amarillo.png', color: '#ffd500' },
  'morus-sp': { icon: 'marker-morus.png', color: '#28316f' },
  'citrus sp': { icon: 'marker-citrus.png', color: '#ffaf1f' },
  'mangifera-sp': { icon: 'marker-naranja.png', color: '#f76619' },
  'mangifera-indica': { icon: 'marker-naranja.png', color: '#f76619' },
  'citrus-tangerina': { icon: 'marker-citrus.png', color: '#ffaf1f' },
  'plantera-vacia': { icon: 'marker-vacia.png', color: '#d6d6d7' },
  'handroanthus-ochraceus': { icon: 'marker-amarillo.png', color: '#ffd500' },
  'tabebuia-rosea': { icon: 'marker-rosa.png', color: '#fb7a9b' },
  'erythrina-variegata': { icon: 'marker-ceibo.png', color: '#e6262b' },
}

export const SPECIES_COLORS: [string, string][] = [
  ['no-determinable', '#a0a0a0'],
  ['no-determinado', '#a0a0a0'],
  ['jacaranda-mimosifolia', '#9798fb'],
  ['persea-americana', '#f8ff92'],
  ['liquidambar- styraciflua', '#f83a3a'],
  ['ceiba-speciosa', '#fb7a9b'],
  ['syagrus-romanzoffiana', '#788059'],
  ['erythrina-cristagalli', '#e6262b'],
  ['morus-alba', '#28316f'],
  ['handroanthus-impetiginosa', '#fb7a9b'],
  ['tabebuia-chrysotricha', '#ffd500'],
  ['ginkgo-biloba', '#f9d11f'],
  ['bauhinia-forficata', '#538036'],
  ['bauhinia-variegata', '#538036'],
  ['peltophorum-dubium', '#ffd500'],
  ['celtis-ehrembergiana', '#e79737'],
  ['acer-palmatum', '#f83a3a'],
  ['acacia-caven', '#ffd500'],
  ['citrus-aurantifolia', '#89b833'],
  ['citrus-aurantium', '#ffaf1f'],
  ['citrus-limon', '#f7d020'],
  ['citrus-paradisi', '#ffdb15'],
  ['citrus-reticulata', '#ffaf1f'],
  ['citrus-sinensis', '#ffaf1f'],
  ['erythrina-falcata', '#e6262b'],
  ['morus-alba-var-pendula', '#28316f'],
  ['morus-nigra', '#28316f'],
  ['tecoma-stans', '#ffd500'],
  ['morus-sp', '#28316f'],
  ['citrus sp', '#ffaf1f'],
  ['mangifera-sp', '#f76619'],
  ['mangifera-indica', '#f76619'],
  ['citrus-tangerina', '#ffaf1f'],
  ['plantera-vacia', '#d6d6d7'],
  ['handroanthus-ochraceus', '#ffd500'],
  ['tabebuia-rosea', '#fb7a9b'],
  ['erythrina-variegata', '#e6262b'],
]

export const SPECIES_ICONS: [string, string][] = [
  ['no-determinable', 'marker-sin-especie.png'],
  ['no-determinado', 'marker-sin-especie.png'],
  ['jacaranda-mimosifolia', 'marker-violeta.png'],
  ['persea-americana', 'marker-palta.png'],
  ['liquidambar- styraciflua', 'marker-rojo.png'],
  ['ceiba-speciosa', 'marker-rosa.png'],
  ['syagrus-romanzoffiana', 'marker-syagrus.png'],
  ['erythrina-cristagalli', 'marker-ceibo.png'],
  ['morus-alba', 'marker-morus.png'],
  ['handroanthus-impetiginosa', 'marker-rosa.png'],
  ['tabebuia-chrysotricha', 'marker-amarillo.png'],
  ['ginkgo-biloba', 'marker-ginkgo.png'],
  ['bauhinia-forficata', 'marker-bauhinia.png'],
  ['bauhinia-variegata', 'marker-bauhinia.png'],
  ['peltophorum-dubium', 'marker-amarillo.png'],
  ['celtis-ehrembergiana', 'marker-tala.png'],
  ['acer-palmatum', 'marker-rojo.png'],
  ['acacia-caven', 'marker-amarillo.png'],
  ['citrus-aurantifolia', 'marker-lima.png'],
  ['citrus-aurantium', 'marker-naranjo-amargo.png'],
  ['citrus-limon', 'marker-limon.png'],
  ['citrus-paradisi', 'marker-pomelo.png'],
  ['citrus-reticulata', 'marker-citrus.png'],
  ['citrus-sinensis', 'marker-naranjo-dulce.png'],
  ['erythrina-falcata', 'marker-ceibo.png'],
  ['morus-alba-var-pendula', 'marker-morus.png'],
  ['morus-nigra', 'marker-morus.png'],
  ['tecoma-stans', 'marker-amarillo.png'],
  ['morus-sp', 'marker-morus.png'],
  ['citrus sp', 'marker-citrus.png'],
  ['mangifera-sp', 'marker-naranja.png'],
  ['mangifera-indica', 'marker-naranja.png'],
  ['citrus-tangerina', 'marker-citrus.png'],
  ['plantera-vacia', 'marker-vacia.png'],
  ['handroanthus-ochraceus', 'marker-amarillo.png'],
  ['tabebuia-rosea', 'marker-rosa.png'],
  ['erythrina-variegata', 'marker-ceibo.png'],
]

export const DEFAULTS: SpeciesStyle = { icon: 'marker-default.png', color: '#5cba9d' }

export function getSpeciesStyle(url?: string): SpeciesStyle {
  if (!url) return DEFAULTS
  return speciesStyles[url] ?? DEFAULTS
}